### ISSUE TITLE
📂Other: user schema need to be refactored

### ISSUE THREAD

**Issue by tejaskh3** [ngoworldcommunity/NGOWorld-Backend#44]
### What would you like to share?

under the user folder both ReportProblemSchema.js and userSceham.js are written with bad practice no camel casing used as done by other part of repo.

![image](https://github.com/MilanCommunity/Milan-Backend/assets/98630752/26e8441e-da4f-4e0c-985b-6f2aa2154421)
![image](https://github.com/MilanCommunity/Milan-Backend/assets/98630752/38fd769a-001d-4610-8bbc-fff5320e83dd)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan-Backend/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan-Backend/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by niranjan-kurhade** [comment]
Please assign me this issue! I would like to work on it.

**Comment by divyansh2375** [comment]
i want to contribute to this project but where are issues ? I mean only 4 issues are present over there . @tamalCodes can you please give me some backend tasks ?
